### ISSUE TITLE
Chrom from_documents not making embedding to remote chromadb server

### ISSUE THREAD

**Issue by umair313** [langchain-ai/langchain#10403]
### System Info

I am runing Django, and chromadb in docker 
Django port 8001
chromadb port 8002

bellow snippet is inside django application on running it, it create a directory named chroma and there is a chroma.sqlite3 file and a dir named with randomly.
it didn't make any call to chromadb's service `chroma` at 8002
```
docs = loader.load()
        emb = OpenAIEmbeddings()
        chroma_settings = Settings()
        chroma_settings.is_persistent = True
        chroma_settings.chroma_server_host = "chroma"
        chroma_settings.chroma_server_http_port = "8002"
        # chroma_settings.persist_directory = "chroma/"

        Chroma.from_documents(
            client_settings=chroma_settings,
            collection_name="chroma_db",
            documents=docs,
            embedding=emb,
            # persist_directory=os.path.join(settings.BASE_DIR, "chroma_db")
        )
```
on running 
`HttpClient(host="chroma", port="8002").list_collections()` return `[]`
running `http://localhost:8002/api/v1/heartbeat` from browser shows `{"nanosecond heartbeat":1694261199976223880}`

versions info

```
langchain==0.0.285
openai==0.27.8
django-jazzmin==2.6.0
tiktoken==0.4.0
jq==1.4.1
chromadb==0.4.*
lark
```
docker-compose

```
version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped
  networks:
    - pharmogene

x-django-build: &django-build
  build:
    context: .
    dockerfile: ./Dockerfile.dev

services:
  django:
    container_name: pharmogene-dc01
    command:
      - bash
      - -c
      - |
        python manage.py collectstatic --no-input
        python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - config/env/dev/.django
    volumes:
      - ./:/code
      - pharmogene_static_volume:/code/static
      - pharmogene_media_volume:/code/media
    depends_on:
      - postgres
      - redis
    <<: [*common,*django-build]

  chroma:
    container_name: pharmogene-cdbc-01
#    image: ghcr.io/chroma-core/chroma:latest
    image: chromadb/chroma:0.4.10.dev2
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8002 --log-config log_config.yml
    volumes:
      - ./:/code
      # Default configuration for persist_directory in chromadb/config.py
      # Currently it's located in "/chroma/chroma/"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
    ports:
      - "8002:8002"
    depends_on:
      - redis
      - postgres
      - django
      - celery
      - celery_beat
    <<: *common

networks:
  pharmogene:
    driver: bridge

volumes:
 ....

```

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

1. install latest version of chromadb and langchain in separate container
2. run chroma in docker using docker hub image
3. try to create embeddings

### Expected behavior

expected behaviour is Httpclient().list_collections() should return list of collections from chroma running inside other container.
