### ISSUE TITLE
Put Langchain on Conda-forge

### ISSUE THREAD

**Issue by darabos** [langchain-ai/langchain#1271]
We manage all our dependencies with a Conda environment file. It would be great if that could cover Langchain too! As Langchain is taking off, there are probably other Conda users in the same shoes.

(Thanks for making Langchain! It's great!)

**Comment by stepp1** [comment]
Using [grayskull](https://github.com/conda/grayskull), we can get a possible recipe by running:
`grayskull pypi --strict-conda-forge langchain`

However, some dependencies are not on conda-forge channels (see not-found.txt). I don't really know if that's really an issue.

**Comment by stepp1** [comment]
For completeness, here's the `meta.yaml` generated by grayskull
```yaml
{% set name = "langchain" %}
{% set version = "0.0.94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain-{{ version }}.tar.gz
  sha256: de1efe486893f2064748366747471854f316a6e9790c0fb6646b8c2e8ed6153f

build:
  entry_points:
    - langchain-server = langchain.server:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - pydantic ^1
    - sqlalchemy ^1
    - requests ^2
    - pyyaml ^6
    - numpy ^1
    - faiss-cpu ^1optionaltrue
    - wikipedia ^1optionaltrue
    - elasticsearch ^8optionaltrue
    - opensearch-py ^2.0.0optionaltrue
    - redis-py ^4optionaltrue
    - manifest-ml ^0.0.1optionaltrue
    - spacy ^3optionaltrue
    - nltk ^3optionaltrue
    - transformers ^4optionaltrue
    - beautifulsoup4 ^4optionaltrue
    - pytorch ^1optionaltrue
    - jinja2 ^3optionaltrue
    - tiktoken ^0optionaltrue
    - pinecone-client ^2optionaltrue
    - weaviate-client ^3optionaltrue
    - google-api-python-client ==2.70.0optionaltrue
    - wolframalpha ==5.0.0optionaltrue
    - anthropic ^0.2.2optionaltrue
    - qdrant-client ^0.11.7optionaltrue
    - dataclasses-json ^0.5.7
    - tensorflow-text ^2.11.0optionaltrue
    - tenacity ^8.1.0
    - cohere ^3optionaltrue
    - openai ^0optionaltrue
    - nlpcloud ^1optionaltrue
    - huggingface_hub ^0optionaltrue
    - google-search-results ^2optionaltrue
    - sentence-transformers ^2optionaltrue
    - aiohttp ^3.8.3
    - pypdf ^3.4.0optionaltrue
    - networkx ^2.6.3optionaltrue
    - aleph-alpha-client ^2.15.0

test:
  imports:
    - langchain
  commands:
    - pip check
    - langchain-server --help
  requires:
    - pip

about:
  home: https://www.github.com/hwchase17/langchain
  summary: Building applications with LLMs through composability
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stepp1
```
