### ISSUE TITLE
ValueError: Redis failed to connect:

### ISSUE THREAD

**Issue by abusufyanvu** [langchain-ai/langchain#13611]
### System Info

# Create and load Redis with documents
vectorstore = RedisVectorStore.from_texts(
    texts=texts,
    metadatas=metadatas,
    embedding=embedding,
    index_name=index_name,
    redis_url=redis_url
)

The error i faced
Redis cannot be used as a vector database without RediSearch >=2.4Please head to https://redis.io/docs/stack/search/quick_start/to know more about installing the RediSearch module within Redis Stack.

### Information

- [ ] The official example notebooks/scripts
- [ ] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

.

### Expected behavior

.

**Comment by pradeepdev-1995** [comment]
any update on this?
@abusufyanvu

**Comment by goodlux** [comment]
has anyone fixed this? I'm having this issue with llamaindex, using redis-server-stack in docker, which appears to have search installed

Failed to initialize: Required Redis db module search 
>= 20600 OR searchlight >= 20600 not installed. See Redis Stack docs at 
https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/.

Have tried everything, I think the error is coming from redisvl

**Comment by infocaominhtien** [comment]
> has anyone fixed this? I'm having this issue with llamaindex, using redis-server-stack in docker, which appears to have search installed
> 
> Failed to initialize: Required Redis db module search
> 
> > = 20600 OR searchlight >= 20600 not installed. See Redis Stack docs at
> > https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/.
> 
> Have tried everything, I think the error is coming from redisvl

I encountered the same issue, and this `docker-compose` file worked for me:

```yaml
services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"  # Redis
      - "8001:8001"  # RedisInsight Web UI
    environment:
      - REDIS_ARGS=--requirepass root
    volumes:
      - D:/coder/manage_database/docker_db/redis_stack/data:/data
```
