### ISSUE TITLE
langchain-mistralai on conda-forge

### ISSUE THREAD

**Issue by Sachin-Bhat** [langchain-ai/langchain#22220]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I ran the following with `grayskull`:
```
grayskull pypi --strict-conda-forge langchain-mistralai
```

and got the following `meta.yml` file:

```
{% set name = "langchain-mistralai" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_mistralai-{{ version }}.tar.gz
  sha256: 44d3fb15ab10b5a04a2cc544d1292af3f884288a59de08a8d7bdd74ce50ddf75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.1.46,<0.3
    - tokenizers >=0.15.1,<1
    - httpx >=0.25.2,<1
    - httpx-sse >=0.3.1,<1

test:
  imports:
    - langchain_mistralai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Mistral and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sachin-Bhat

```

one thing to note is that `httpx-sse` is also not available on conda-forge.

### Description

I tried to install langchain-mistralai using conda but was unable to do so as the package was not available on conda-forge.

### System Info

this is not relevant to the bug.
