### ISSUE TITLE
Add docstring linting to core, langchain, partner packages

### ISSUE THREAD

**Issue by baskaryan** [langchain-ai/langchain#23188]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

We want to add docstring linting to langchain-core, langchain, langchain-text-splitters, and partner packages. This requires adding this to each pacakages pyproject.toml

```toml
[tool.ruff.lint]
select = [
  ...
  "D",    # pydocstyle
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"tests/**" = ["D"]  # ignore docstring checks for tests
```

this will likely cause a number of new linting errors which then need to be fixed. there should be a separate pr for each package. here's a reference for langchain-openai (linting errors have not yet been fixed) https://github.com/langchain-ai/langchain/pull/23187
