### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/how_to/extraction_examples/>

### ISSUE THREAD

**Issue by Tirth27** [langchain-ai/langchain#23396]
### URL

https://python.langchain.com/v0.2/docs/how_to/extraction_examples/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Here's a revised version of your report description:

I attempted the example provided in the given link. While it executed flawlessly with OpenAI, I encountered a `TypeError` when running it with Cohere.

The error message was: `TypeError: BaseCohere.chat() received an unexpected keyword argument 'method'`.

### Idea or request for content:

I believe the document is not current with the Cohere chat and requires some amendments.

**Comment by Tirth27** [comment]
Below is the snippet from my `pyproject.toml` package versions:
```toml
python = "^3.12.3"
langchain = "0.2.5"
langgraph = "^0.0.69"
pydantic-settings = "^2.2.1"
langchain-cohere = "0.1.8"
tiktoken = "0.7.0"
chromadb = "^0.5.0"
langchain-openai = "^0.1.8"
langchain-community = "^0.2.5"
langchain-core = "^0.2.9"
```
