### ISSUE TITLE
DOC: Documentation for testing documentation changes does not work

### ISSUE THREAD

**Issue by bovlb** [langchain-ai/langchain#28836]
### URL

https://python.langchain.com/docs/contributing/how_to/documentation/setup/

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The command:
> poetry install --with lint,docs --no-root

produces the output:
> Group(s) not found: docs (via --with)

**Comment by Uvi-12** [comment]
I followed the errors and made some changes in the code:

### Changed Code:
```toml
# Before:
langchain-core = { path = "libs/core/", develop = true, version = "^0.3.27" }

# After:
langchain-core = { path = "libs/core/", develop = true }
```

### Added Code:
```toml
[tool.poetry.group.docs.dependencies]
sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"
```

Then I ran `poetry install --with lint,docs --no-root`, which gave this error:

```
pyproject.toml changed significantly since poetry.lock was last generated. Run `poetry lock [--no-update]` to fix the lock file.
```

I followed it and ran `poetry lock --no-update`. After its completion, I ran `poetry install --with lint,docs --no-root`, and I guess it worked properly, below is an attached screenshot after running `poetry install --with lint,docs --no-root` (correct me if I am wrong)

<img width="1319" alt="Screenshot 2024-12-20 at 12 28 15 PM" src="https://github.com/user-attachments/assets/4e440dd8-5612-4cad-8b14-6f56d2fe6e39" />



Please let me know if this is a correct fix.
