### ISSUE TITLE
Thought about a docker-compose file to run langchain's whole ecosystem?

### ISSUE THREAD

**Issue by Ryangr0** [langchain-ai/langchain#3150]
I'm talking about langchain, langchain-backend and langchain-frontend here. 

https://python.langchain.com/en/latest/tracing/local_installation.html

Could give people a starting off point if they want to use langchain with tracing. I'll share mine here:

```
version: '3.7'

services:

  your-app-name-containing-langchain:
    container_name: your-app-name-containing-langchain
    image: your/image
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
      env_file: .env
    volumes:
      - ./:/app

  langchain-frontend:
    container_name: langchain-frontend
    image: notlangchain/langchainplus-frontend:latest
    ports:
      - 4173:4173
    environment:
      - BACKEND_URL=http://langchain-backend:8000
      - PUBLIC_BASE_URL=http://localhost:8000
      - PUBLIC_DEV_MODE=true
    depends_on:
      - langchain-backend

  langchain-backend:
    container_name: langchain-backend
    image: notlangchain/langchainplus:latest
    environment:
      - PORT=8000
      - LANGCHAIN_ENV=local
    ports:
      - 8000:8000
    depends_on:
      - langchain-db

  langchain-db:
    container_name: langchain-db
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
```

**Comment by AdamShamlian** [comment]
You got this working with <your_app> hosted on a separate docker container? I can get <my_app> and the langchain-frontend to work independently, but even looking at the "default" session, I see no chain runs. Note, in my apps, .env file, I have `LANGCHAIN_TRACING=true`.

**Comment by Ryangr0** [comment]
```

```

> You got this working with <your_app> hosted on a separate docker container? I can get <my_app> and the langchain-frontend to work independently, but even looking at the "default" session, I see no chain runs. Note, in my apps, .env file, I have `LANGCHAIN_TRACING=true`.

Not entirely sure what you mean here, but for a docker container to be able to see other containers they need to share a network. Are you running your app container independently from your docker-compose file? Is that what you mean?

**Comment by AdamShamlian** [comment]
Nope, my app's container is part of the dc file. I independently arrived at nearly identical file as the one you posted above, actually:
```
version: '3.7'
services:

  prototype:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ../..:/workspaces:cached # using this through vscode devcontainers
    command: sleep infinity
    env_file: 
      - devcontainer.env # see above (LANGCHAIN_TRACING=true, among other vars, is set in here)

  langchain-frontend:
    image: notlangchain/langchainplus-frontend:latest
    ports:
      - 4173:4173
    environment:
      - BACKEND_URL=http://langchain-backend:8000
      - PUBLIC_BASE_URL=http://localhost:8000
      - PUBLIC_DEV_MODE=true
    depends_on:
      - langchain-backend

  langchain-backend:
    image: notlangchain/langchainplus:latest
    environment:
      - PORT=8000
      - LANGCHAIN_ENV=local
    ports:
      - 8000:8000
    depends_on:
      - langchain-db
      
  langchain-db:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    expose:
      - 5432:5432
```
This allows me to navigate to `127.0.0.1:8001` to interact with my application (and trigger chain runs), and it also allows me to navigate to `127.0.0.1:4173` to interact with the langchain-frontend. However, upon interaction (after chain runs), I have an empty frontend. 

Was wondering if there was something obvious I was missing, prior to, say digging into the database in the postgres container, etc.
