### ISSUE TITLE
openapi_spec_to_openai_fn generates Date objects which are not JSON serializable

### ISSUE THREAD

**Issue by paschembri** [langchain-ai/langchain#6671]
### System Info

v0.0.211

### Who can help?

@hw

### Information

- [X] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [ ] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [X] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

Use an OpenAPI spec which contains a key `format` with a known type like `date`.

```yaml
    date_de_naissance_dirigeant_min:
      name: date_de_naissance_dirigeant_min
      in: query
      description: Date de naissance minimale du dirigeant (ou de l'un des dirigeants de l'entreprise pour une recherche d'entreprises), au format JJ-MM-AAAA.
      required: false
      schema:
        type: string
        format: date
        example: 1970-01-01
```

This gets translated into 

```python
'date_de_naissance_dirigeant_min': {
          'type': 'string',
          'schema_format': 'date',
          'description': "Date de naissance minimale du dirigeant (ou de l'un des dirigeants de l'entreprise pour une recherche d'entreprises), au format JJ-MM-AAAA.",
          'example': datetime.date(1970, 1, 1),
      },
```

### Expected behavior

No objects other that strings and lists should be instanciated by `openapi_spec_to_openai_fn`
